# This is a config for E2B sandbox template.
# You can use template ID (2043yrdcgqc7k99152nd) or template name (vibe-nextjs-test-09132247) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-09132247") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-09132247") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-09132247')

team_id = "c687cdcf-55f6-4c65-8edc-f1773868dcbf"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-09132247"
template_id = "2043yrdcgqc7k99152nd"
